### ISSUE TITLE
Investigate import hints

### ISSUE THREAD

**Issue by piotmag769** [starkware-libs/cairols-issues#5]
Currently it does work for `core` crate only, doesn't seem to work e.g. for `snforge_std`. Mind that hints marked with `abc` are dictionary hints that are done by vscode client, not LS itself.

![Image](https://github.com/user-attachments/assets/c4e6185d-1f24-475c-bd4a-d64bfb1a536b)

**Comment by Draggu** [comment]
![image](https://github.com/user-attachments/assets/3feae6c8-af61-4538-9fb7-2772ea3f1b46)
Can not reproduce
